version: '3'

services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mkdocs-container
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    working_dir: /code
    command:
      - "mike"
      - "serve"
      - "--dev-addr=0.0.0.0:8000"