site_name: VketCloudSDK Manual
site_description: 'VketCloudSDKのマニュアルです'
site_author: 'HIKKY'

theme:
  favicon: images/VketCloudIcon.png
  logo: images/VketCloudIcon.png
  name: material
  palette:
  - scheme: default
    primary: blue
    accent: blue
    toggle:
        icon: material/toggle-switch-off-outline
        name: ダークモードに切り替えます。
  - scheme: slate
    primary: blue
    accent: blue
    toggle:
        icon: material/toggle-switch
        name: ライトモードに切り替えます。
  features:
    - navigation.indexes
    - header.autohide
    - search.suggest
    - search.highlight
  footer:
    logo: images/HikkyLogo.png
    copyright: ©HIKKY Co.,Ltd. All rights reserved.
  analytics:
    gtag: G-05NPW204YY
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  nav_style: dark
  custom_dir: custom_theme

extra:
  generator: false
  version:
    provider: mike
    default: latest
  homepage: https://www.hikky.co.jp/vketcloud
  analytics: 
    provider: google
    property: G-R753QL60GW
    
use_directory_urls: false

plugins:
  - search:
      lang: 
        - en
        - ja
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null
  - i18n:
      default_language: ja
      languages:
        en: English
        ja: 日本語
      nav_translations:
        ja:
          # 概要
          Introduction: はじめに
          # VketCloudSDKについて
          About VketCloudSDK: VketCloudSDKについて
          Setup Account: アカウント準備
          Operating Environment: 動作環境
          Setup SDK: SDKの導入方法
          Login to SDK: SDKにログインする
          How to use avatar: アバターの使用方法
          # ワールド制作の基本
          First Steps: ワールド制作の基本
          Essential Objects: ワールドの基本要素
          Build And Run: ローカル環境でのビルドと実行
          World Upload: ワールドアップロード
          # Vket Cloud Settings    
          Vket Cloud Settings - Overview: Vket Cloud Settings - 概要
          # ワールド制作ガイド
          World Making Guide: ワールド制作ガイド
          Avatar File: アバターファイル
          Specifications Limits : VketCloudの仕様制限
          HEOExporter: .heoファイルについて
          HEOExporter Tutorial: .heoファイルを出力する
          Reflection Probe: リフレクションプローブ
          Skybox: スカイボックス設定
          Texture Compression: テクスチャ圧縮
          How to use Colliders / Tips: コライダーの使い方 / Tips
          Physics Engine: 物理エンジンの使い方
          Tips on using HEOField: HEOFieldの使い方
          Unity settings for replicating actual look in Vket Cloud: UnityとVketCloudの見た目を揃える
          Mesh Collider: メッシュコライダーについて
          Adding Preset Avatars : プリセットアバターを追加する
          How to Animate Objects: オブジェクトをアニメーションさせる
          How to Animate Objects - Troubleshooting: オブジェクトをアニメーションさせる - 動かないときは
          # ActionNodeGraph: アクションノードグラフ
          # トラブルシューティング
          Trouble shooting: トラブルシューティング
          Trouble shooting - General Checklist: SDK初学者:何か起きたときにとりあえず見るべきリスト
          SDK does not appear after install: SDKがインストール後に立ち上がらない
          Build Error / How to troubleshoot issues: ビルドエラー / ワールドが動かないときは
          Version Update Troubleshooting: バージョンアップ後によくあるトラブル
          # SDKTools
          Particle Editor : パーティクルエディター
          Particle Editor - Overview: パーティクルエディター：概要 
          About Screen / How to Operate: ウィンドウ解説・操作方法について
          Particle Editor - Properties: パーティクルエディター：プロパティ一覧
          Animation Converter : アニメーションコンバーター
          Debug Mode: デバッグモード
          Debug Console: デバッグコンソール
          Debug Messages: デバッグメッセージ一覧
          # 編集Tips
          World Editing Tips: 編集のためのTips
          Quick Menu for adding Vket Cloud objects: Vket Cloudオブジェクト追加のためのクイックメニュー
          Using EditorOnly Tags: EditorOnlyタグの使用方法
          Editing Multiple HEOComponents: 複数のHEOコンポーネントの一括編集
          Disable Contribute GI of Unlit Materials: UnlitマテリアルのContributeGI設定を外す
          Build Options: ビルド時のオプション
          # 軽量化
          World Optimization: ワールドの軽量化方法
          World Optimization - Overview: ワールドの軽量化方法：概要
          Occlusion Culling: オクルージョンカリング
          Optimization for Smartphones: スマートフォンのためのワールド軽量化
          # HEOComponents
          HEOComponents: HEOコンポーネント
          # アクション
          Actions: アクションについて
          Actions Overview: アクションの概要
          # HeliScript
          HeliScript - Overview: HeliScript概要
          Statements and flow control: 文法と制御構文
          Declarations and definitions: 定義・宣言
          Control Statement: 制御構文
          Reference (ref): 参照(ref)
          Constant Variable (const): 定数(const)
          Built-in Types: 組み込み型
          Basic Types: 基本型
          String: 文字列(String)
          List: 配列(List)
          Delegate: デリゲート(Delegate)
          Operator: 演算子
          Class: クラス
          Components / Callback functions: コンポーネント / コールバック関数
          Item Types and Usable Functions: Itemの種類一覧 / HeliScript関数対応表
          Built-in Classes And Functions: 組み込みクラス・関数
          Vector3: Vector3クラス
          Quaternion: Quaternionクラス
          Matrix: Matrixクラス
          Item: Itemクラス
          Player: Playerクラス
          Built-in Functions: 組み込み関数
          System: システム
          Math: 数学
          Network: ネットワーク
          NamePlate: ネームプレート
          GUI: GUI
          TextChat: テキストチャット
          Physics: 物理演算
          Camera: カメラ
          Common Dialog: 汎用ダイアログ
          # チェンジログ / リリースノート
          Change Log: チェンジログ
          About Changelog: チェンジログについて
          Release Note: リリースノート
          About Release Note: リリースノートについて
          # Misc
          License: 利用規約

markdown_extensions:
    - admonition
    - codehilite
    - attr_list

nav:
- Introduction: index.md
- About VketCloudSDK:
    - Setup Account : AboutVketCloudSDK/SetupAccount.md
    - Operating Environment : AboutVketCloudSDK/OperatingEnvironment.md
    - Setup SDK : AboutVketCloudSDK/SetupSDK_external.md
    - Login to SDK: AboutVketCloudSDK/LoginSDK.md
    - How to use avatar : AboutVketCloudSDK/SetupAvatar.md
- First Steps:
    - Essential Objects : FirstStep/WorldBasicComponents.md
    - Build And Run : FirstStep/BuildAndRun.md
    - World Upload : FirstStep/WorldUpload.md
- Vket Cloud Settings:
    - Vket Cloud Settings - Overview: VketCloudSettings/Overview.md
    # Basic
    - Basic Settings: VketCloudSettings/BasicSettings.md
    - Player Settings: VketCloudSettings/PlayerSettings.md
    - Despawn Height Settings: VketCloudSettings/DespawnHeightSettings.md
    # Advanced
    - Camera Settings: VketCloudSettings/CameraSettings.md
    - Rendering Settings: VketCloudSettings/RenderingSettings.md
    - Avatar Settings: VketCloudSettings/AvatarSettings.md
    - MyAvatar Settings: VketCloudSettings/MyAvatarSettings.md
- World Making Guide:
    - Specifications Limits : WorldMakingGuide/UnityGuidelines.md
    - Skybox : WorldMakingGuide/Skybox.md 
    - How to use Colliders / Tips : WorldMakingGuide/Collider.md
    - Physics Engine: WorldMakingGuide/PhysicsEngine.md
    - Tips on using HEOField: WorldMakingGuide/HEOFieldTips.md
    - Reflection Probe : WorldMakingGuide/ReflectionProbe.md
    #- ChatGPT: WorldMakingGuide/ChatGPT.md #整備中
    - How to Animate Objects: WorldMakingGuide/PropAnimation.md
    - How to Animate Objects - Troubleshooting: WorldMakingGuide/PropAnimation_TroubleShooting.md
    - Avatar File: WorldMakingGuide/AvatarFile.md
    - Adding Preset Avatars : WorldMakingGuide/PresetAvatar.md
- Trouble shooting:
    - SDK does not appear after install : troubleshooting/InstallingDeeplink.md
    - Trouble shooting - General Checklist: troubleshooting/GeneralChecklist.md
    - Build Error / How to troubleshoot issues: troubleshooting/BuildError.md
    - Version Update Troubleshooting: troubleshooting/VersionUpdateTroubleshooting.md
    - Unity settings for replicating actual look in Vket Cloud : heoexporter/he_align_unity_to_vketcloud.md
- SDK Tools:
    - Debug Console: debugconsole/debugconsole.md
    - Debug Messages: debugconsole/debugmessage.md
    - Debug Mode: WorldEditingTips/DebugMode.md
    - HEOExporter Tutorial : WorldMakingGuide/HEOExporter_Tutorial.md
    - Animation Converter : HEMAnimationConverter/AnimationConverter.md
    - Particle Editor :
      - Particle Editor - Overview : particleeditor/pe_about_particleeditor.md
      - About Screen / How to Operate : particleeditor/pe_about_screen.md
      - Particle Editor - Properties : particleeditor/pe_about_properties.md
    - Export Compressed Texture : SDKTools/ExportCompressedTexture.md
    - VKC Activity Exporter : SDKTools/VKCActivityExporter.md
    - Texture Import Viewer: SDKTools/TextureImportViewer.md
- World Editing Tips:
  - Quick Menu for adding Vket Cloud objects: WorldEditingTips/QuickMenu.md
  - Using EditorOnly Tags: WorldEditingTips/EditorOnlyTag.md
  - Editing Multiple HEOComponents: WorldEditingTips/MultiSelect_HEOComponents.md
  - Disable Contribute GI of Unlit Materials: WorldEditingTips/DisableContributeGITool.md
  - Build Options: WorldEditingTips/BuildOptions.md
- World Optimization: 
  - World Optimization - Overview : WorldOptimization/WorldOptimization.md
  - Occlusion Culling : WorldOptimization/OcclusionCulling.md
  - Texture Compression : WorldOptimization/TextureCompression.md
  - Optimization for Smartphones: WorldOptimization/SmartphoneOptimization.md
- HEOComponents:
    - HEOActionTrigger: HEOComponents/HEOActionTrigger.md
    - HEOActivity: HEOComponents/HEOActivity.md
    - HEOAnimation: HEOComponents/HEOAnimation.md
    - HEOAreacollider: HEOComponents/HEOAreacollider.md
    - HEOAudio: HEOComponents/HEOAudio.md
    - HEOBackgroundTexture: HEOComponents/HEOBackgroundTexture.md
    - HEOCamera: HEOComponents/HEOCamera.md
    - HEOCollider: HEOComponents/HEOCollider.md
    - HEOClickGuide: HEOComponents/HEOClickGuide.md
    - HEODespawnHeight: HEOComponents/HEODespawnHeight.md
    - HEOField: HEOComponents/HEOField.md
    #- HEOInfo: HEOComponents/HEOInfo.md #整備中
    - HEOLODLevel: HEOComponents/HEOLODLevel.md
    - HEOMeshCollider: HEOComponents/HEOMeshCollider.md
    - HEOMirror: HEOComponents/HEOMirror.md
    - HEONameplate: HEOComponents/HEONameplate.md
    - HEOObject: HEOComponents/HEOObject.md
    #- HEOObjectType: HEOComponents/HEOObjectType.md #整備中
    - HEOParticle: HEOComponents/HEOParticle.md
    - HEOPlane: HEOComponents/HEOPlane.md
    - HEOPlayer: HEOComponents/HEOPlayer.md
    - HEOReflectionProbe : HEOComponents/HEOReflectionProbe.md
    - HEOScript: HEOComponents/HEOScript.md
    - HEOShadow: HEOComponents/HEOShadow.md
    - HEOShowFlag : HEOComponents/HEOShowFlag.md
    - HEOSpawn: HEOComponents/HEOSpawn.md
    - HEOSpot: HEOComponents/HEOSpot.md
    - HEOTextPlane: HEOComponents/HEOTextPlane.md
    - HEOUVScroller: HEOComponents/HEOUVScroller.md
    - HEOVideoTrigger: HEOComponents/HEOVideoTrigger.md
    - HEOWorldSetting: HEOComponents/HEOWorldSetting.md
- Actions: 
    #- ActionNodeGraph: Actions/ActionNodeGraph.md #整備のために一旦取り下げ
    - Actions Overview: Actions/ActionsOverview.md
    - System:
      - Openweb: Actions/System/Openweb.md
      - StopVideo: Actions/System/StopVideo.md
      - Wait: Actions/System/Wait.md
      - Warp: Actions/System/Warp.md
      - Enter/LeaveVoiceGroup: Actions/System/EnterLeaveVoiceGroup.md
      - WhiteOut/In: Actions/System/WhiteOutIn.md
      - FadeOut/In: Actions/System/FadeOutIn.md
    - Node:
      - Show/HideNode: Actions/Node/ShowHideNode.md
      - Enable/DisableClickableNode: Actions/Node/EnableDisableClickableNode.md
      - Enable/DisableCollider: Actions/Node/EnableDisableCollider.md
    - Item:
      - Play/StopItem: Actions/Item/PlayStopItem.md
      - Show/HideItem: Actions/Item/ShowHideItem.md
      - SetPosRelativePlayer: Actions/Item/SetPosRelativePlayer.md
      - MoveTo: Actions/Item/MoveTo.md
    - Avatar:
      - Play/StopObject: Actions/Avatar/PlayStopObject.md
      - Show/HideObject: Actions/Avatar/ShowHideObject.md
      - Emote: Actions/Avatar/Emote.md
      - Motion: Actions/Avatar/Motion.md
      - NextMotion: Actions/Avatar//NextMotion.md
    - Physics:
      - AddVelocity: Actions/Physics/PhysicsAddVelocity.md
      - Add / ClearForce: Actions/Physics/PhysicsClearAddForce.md
      - SetPhysicsEnable: Actions/Physics/PhysicsSetEnable.md
      - SetPosition / Rotation: Actions/Physics/PhysicsSetPosRot.md
    - Programmatic:
      - AddVar: Actions/Programmatic/AddVar.md
      - SetVar: Actions/Programmatic/SetVar.md
      - If Variable Equal To Value: Actions/Programmatic/IfEqual.md
      - If Variable Not Equal To Value: Actions/Programmatic/IfNotEqual.md
      - If Variable More Than Value: Actions/Programmatic/IfMoreThan.md
      - If Variable Less Than Value: Actions/Programmatic/IfLessThan.md
      - Random: Actions/Programmatic/Random.md
      - SetCookieText: Actions/Programmatic/SetCookieText.md
      - CallScript: Actions/Programmatic/CallScript.md
- HeliScript:
    - HeliScript - Overview: hs/hs_overview.md
    - Built-in Types:
        - Basic Types: hs/hs_var.md
        - String: hs/hs_string.md
        - List: hs/hs_list.md
        - Delegate: hs/hs_delegate.md
    - Class: hs/hs_class.md
    - Components / Callback functions: hs/hs_component.md
    - Item Types and Usable Functions: hs/hs_item_types_functions.md
    - Built-in Classes And Functions:
        - Vector3: hs/hs_struct_vector3.md
        - Quaternion: hs/hs_struct_quaternion.md
        - Matrix: hs/hs_struct_matrix.md
        - Item: hs/hs_class_item.md
        - Player: hs/hs_class_player.md
    - Built-in Functions:
        - System: hs/hs_system_function.md
        - Math: hs/hs_system_function_math.md
        - Network: hs/hs_system_function_net.md
        - NamePlate: hs/hs_system_function_nameplate.md
        - GUI: hs/hs_system_function_gui.md
        - TextChat: hs/hs_system_function_textchat.md
        - ChatGPT: hs/hs_system_function_chatgpt.md
        - Physics: hs/hs_system_function_physics.md
        - Camera: hs/hs_system_function_camera.md
        - Common Dialog: hs/hs_system_function_commondialog.md
    - Statements and flow control:
        - Declarations and definitions: hs/hs_statement_def.md
        - Control Statement: hs/hs_statement_control.md
        - Operator: hs/hs_operator.md
- Release Note:
    - About Release Note: releasenote/AboutReleasenote.md
    - v12.x:
        - v12.3: releasenote/releasenote-12.3.md
        - v12.2: releasenote/releasenote-12.2.md
        - v12.1: releasenote/releasenote-12.1.md
        - v12.0: releasenote/releasenote-12.0.md
    - v9.x:
        - v9.11: releasenote/releasenote-9.11.md
        - v9.10: releasenote/releasenote-9.10.md
        - v9.9: releasenote/releasenote-9.9.md
        - v9.8: releasenote/releasenote-9.8.md
        - v9.7: releasenote/releasenote-9.7.md
        - v9.6: releasenote/releasenote-9.6.md
        - v9.5: releasenote/releasenote-9.5.md
        - v9.4: releasenote/releasenote-9.4.md
        - v9.3: releasenote/releasenote-9.3.md
        - v9.2: releasenote/releasenote-9.2.md
        - v9.1: releasenote/releasenote-9.1.md
        - v9.0: releasenote/releasenote-9.0.md
    - v8.x:
        - v8.2: releasenote/releasenote-8.2.md
        - v8.1: releasenote/releasenote-8.1.md
        - v8.0: releasenote/releasenote-8.0.md
    - v7.x:
        - v7.3: releasenote/releasenote-7.3.md
        - v7.2: releasenote/releasenote-7.2.md
        - v7.1: releasenote/releasenote-7.1.md
        - v7.0: releasenote/releasenote-7.0.md
    - v6.x:
        - v6.4: releasenote/releasenote-6.4.md
        - v6.3: releasenote/releasenote-6.3.md
        - v6.2: releasenote/releasenote-6.2.md
        - v6.1: releasenote/releasenote-6.1.md
        - v6.0: releasenote/releasenote-6.0.md
    - v5.x:
        - v5.5: releasenote/releasenote-5.5.md
        - v5.4: releasenote/releasenote-5.4.md
        - v5.3: releasenote/releasenote-5.3.md
        - v5.2: releasenote/releasenote-5.2.md
        - v5.1: releasenote/releasenote-5.1.md
        - v5.0: releasenote/releasenote-5.0.md
    - v4.x:
        - v4.8: releasenote/releasenote-4.8.md
        - v4.7: releasenote/releasenote-4.7.md
        - v4.6: releasenote/releasenote-4.6.md
        - v4.5: releasenote/releasenote-4.5.md
        - v4.4: releasenote/releasenote-4.4.md
        - v4.3: releasenote/releasenote-4.3.md
        - v4.2: releasenote/releasenote-4.2.md
        - v4.1: releasenote/releasenote-4.1.md
        - v4.0: releasenote/releasenote-4.0.md
    - v3.x:
        - v3.9: releasenote/releasenote-3.9.md  
        - v3.8: releasenote/releasenote-3.8.md
        - v3.7: releasenote/releasenote-3.7.md
        - v3.6: releasenote/releasenote-3.6.md
        - v3.5: releasenote/releasenote-3.5.md
        - v3.4: releasenote/releasenote-3.4.md
        - v3.3: releasenote/releasenote-3.3.md
        - v3.2: releasenote/releasenote-3.2.md
- Change Log:
    - About Changelog: changelog/AboutChangelog.md
    - v12.x:
        - v12.3: changelog/changelog-12.3.md
        - v12.1: changelog/changelog-12.1.md
        - v12.0: changelog/changelog-12.0.md
    - v9.x:
        - v9.11: changelog/changelog-9.11.md
        - v9.5: changelog/changelog-9.5.md
        - v9.4: changelog/changelog-9.4.md
        - v9.3: changelog/changelog-9.3.md
        - v9.2: changelog/changelog-9.2.md
        - v9.1: changelog/changelog-9.1.md
        - v9.0: changelog/changelog-9.0.md
    - v8.x:
        - v8.2: changelog/changelog-8.2.md
        - v8.1: changelog/changelog-8.1.md
        - v8.0: changelog/changelog-8.0.md
    - v7.x:
        - v7.3: changelog/changelog-7.3.md
        - v7.2: changelog/changelog-7.2.md
        - v7.1: changelog/changelog-7.1.md
        - v7.0: changelog/changelog-7.0.md
    - v6.x:
        - v6.4: changelog/changelog-6.4.md
        - v6.3: changelog/changelog-6.3.md
        - v6.2: changelog/changelog-6.2.md
        - v6.1: changelog/changelog-6.1.md
        - v6.0: changelog/changelog-6.0.md
    - v5.x:
        - v5.5: changelog/changelog-5.5.md
        - v5.4: changelog/changelog-5.4.md
        - v5.3: changelog/changelog-5.3.md
        - v5.2: changelog/changelog-5.2.md
        - v5.1: changelog/changelog-5.1.md
        - v5.0: changelog/changelog-5.0.md
    - v4.x:
        - v4.8: changelog/changelog-4.8.md
        - v4.7: changelog/changelog-4.7.md
        - v4.6: changelog/changelog-4.6.md
        - v4.5: changelog/changelog-4.5.md
        - v4.4: changelog/changelog-4.4.md
        - v4.3: changelog/changelog-4.3.md
        - v4.2: changelog/changelog-4.2.md
        - v4.1: changelog/changelog-4.1.md
        - v4.0: changelog/changelog-4.0.md
    - v3.x:
        - v3.9: changelog/changelog-3.9.md  
        - v3.8: changelog/changelog-3.8.md
        - v3.7: changelog/changelog-3.7.md
        - v3.6: changelog/changelog-3.6.md
        - v3.5: changelog/changelog-3.5.md
        - v3.4: changelog/changelog-3.4.md
        - v3.3: changelog/changelog-3.3.md
        - v3.2: changelog/changelog-3.2.md
- License: common/License.md
