site_name: VketCloudSDK Manual
site_description: 'VketCloudSDKのマニュアルです'
site_author: 'HIKKY'

theme:
  favicon: images/VketCloudIcon.png
  logo: images/VketCloudIcon.png
  name: material
  palette:
  - scheme: default
    primary: blue
    accent: blue
    toggle:
        icon: material/toggle-switch-off-outline
        name: ダークモードに切り替えます。
  - scheme: slate
    primary: blue
    accent: blue
    toggle:
        icon: material/toggle-switch
        name: ライトモードに切り替えます。
  features:
    - navigation.indexes
    - header.autohide
    - search.suggest
    - search.highlight
  footer:
    logo: images/HikkyLogo.png
    copyright: ©HIKKY Co.,Ltd. All rights reserved.
  analytics:
    gtag: G-05NPW204YY
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  nav_style: dark
  custom_dir: custom_theme

extra:
  generator: false
  version:
    provider: mike
    default: latest
  homepage: https://www.hikky.co.jp/vketcloud
  
use_directory_urls: false

plugins:
  - search:
      lang: 
        - en
        - ja
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null
  - i18n:
      default_language: en
      languages:
        en: English
        ja: 日本語
      nav_translations:
        ja:
          Introduction: はじめに
          About VketCloudSDK: VketCloudSDKについて
          Setup Account: アカウント準備
          Operating Environment: 動作環境
          Build And Run: ビルド方法
          World Upload: ワールドアップロード
          Setup SDK: SDKの導入方法
          How to use avatar: アバターの使用方法
          Essential Objects: ワールドの基本要素
          Skybox: スカイボックス設定
          Statements And Flow Control: 文法・制御構文
          Declarations and definitions: 定義・宣言
          Control Statement: 制御構文
          Reference (ref): 参照(ref)
          Constant Variable (const): 定数(const)
          Built-in Types: 組み込み型
          Basic Types: 基本型
          String: 文字列(String)
          List: 配列(List)
          Operator: 演算子
          Class: クラス
          Component: コンポーネント
          Built-in Classes And Functions: 組み込みクラス・関数
          Vector3: Vector3クラス
          Quaternion: Quaternionクラス
          Matrix: Matrixクラス
          Item: Itemクラス
          Player: Playerクラス
          Built-in Functions: 組み込み関数
          System: システム
          Math: 数学
          Network: ネットワーク
          NamePlate: ネームプレート
          GUI: GUI
          TextChat: テキストチャット
          HEOExporter: .heoファイルについて
          HEOExporter Tutorial: .heoファイルを出力する
          Specifications Limits : VketCloudの仕様制限
          ReflectionProbe: 反射を写り込ませるには
          Texture Compression: テクスチャ圧縮
          Physics Engine: 物理エンジン
          Auto Texture Compression: 自動テクスチャ圧縮
          Unity settings for replicating actual look in Vket Cloud: UnityとVketCloudの見た目を揃える
          Mesh Collider: メッシュコライダーについて
          HEOComponents: HEOコンポーネント
          About VketCloudSDK: VketCloudSDKについて
          OperatingEnvironment: 動作環境
          SetupSDK: 導入方法
          BuildAndRun: ビルド
          WorldUpload: アップロード
          License: 利用規約
          Loading stops: ブラウザの読み込みが止まる
          Actions: アクションについて
          Actions Overview: アクションの概要
          ActionNodeGraph: アクションノードグラフ
          Particle Editor : パーティクルエディター
          ParticleEditor Overview: パーティクルエディター概要 
          About Screen: 操作画面について
          Operation: 操作説明
          Window Info: ウィンドウ解説
          Toolbar: ツールバー
          Property: プロパティウィンドウ
          Animation Converter : アニメーションコンバーター
          Adding Preset Avatars : プリセットアバターを追加する
          Trouble shooting: トラブルシューティング
          SDK does not appear after install: SDKがインストール後に立ち上がらない
          Build Error: ビルドエラー
          Browser does not open: ブラウザが立ち上がらない
          Browser window blackouts: ブラウザウィンドウが暗転したまま動かない
          Changes are not applied: 変更が更新されない
          World URL does not open the world: ワールドURLを使用してワールドが開けない
          Missing Components After Version Update: バージョンアップ後にComponentがMissingとして表示される
          Private room indication disappears on reloading the world check page: アップロードしたワールドの確認時にリロードするとPrivateの表記が消える
          First Step: ワールド制作の基本
          Release Note: リリースノート
          Change Log: チェンジログ
          HeliScript: ヘリスクリプト
          Statements and flow control: 宣言と制御
          Check Tool: チェックツール
          World Making Guide: ワールド制作ガイド
          Avatar File: アバターファイル
          Utility Tools: 補助ツールの使い方
          Login to SDK: SDKにログインする

markdown_extensions:
    - admonition
    - codehilite
    - attr_list

nav:
- Introduction: index.md
- About VketCloudSDK:
    - Setup Account : AboutVketCloudSDK/SetupAccount.md
    - Operating Environment : AboutVketCloudSDK/OperatingEnvironment.md
    - Setup SDK : AboutVketCloudSDK/SetupSDK_external.md
    - Login to SDK: AboutVketCloudSDK/LoginSDK.md
    - How to use avatar : AboutVketCloudSDK/SetupAvatar.md
- First Step:
    - Essential Objects : FirstStep/WorldBasicComponents.md
    - Build And Run : FirstStep/BuildAndRun.md
    - World Upload : FirstStep/WorldUpload.md
- World Making Guide:
    - Specifications Limits : WorldMakingGuide/UnityGuidelines.md
    - Skybox : WorldMakingGuide/Skybox.md 
    #- How to Set Collider : WorldMakingGuide/Collider.md #未記載
    - Physics Engine : WorldMakingGuide/PhysicsEngine.md
    - ReflectionProbe : WorldMakingGuide/ReflectionProbe.md
    - Avatar File: WorldMakingGuide/AvatarFile.md
    - HEOExporter Tutorial : WorldMakingGuide/HEOExporter_Tutorial.md
    - Check Tool: checktool/checktool.md
    - Auto Texture Compression: AutoTextureCompresser/AutoTextureCompresser.md
    - Texture Compression : heoexporter/he_TextureCompression.md
    - Particle Editor :
      - ParticleEditor Overview : particleeditor/pe_about_particleeditor.md
      - About Screen : particleeditor/pe_about_screen.md
      - Operation: particleeditor/pe_control.md
      - Window Info:
        - Toolbar : particleeditor/pe_toolbar.md
        - Property : particleeditor/pe_propertywindow.md
        - Particle List : particleeditor/pe_particlelistwindow.md
    - Animation Converter : HEMAnimationConverter/AnimationConverter.md
    - Adding Preset Avatars : WorldMakingGuide/PresetAvatar.md
- HEOComponents:
    - HEOWorldSetting: HEOComponents/HEOWorldSetting.md
    - HEOField: HEOComponents/HEOField.md
    - HEOPlayer: HEOComponents/HEOPlayer.md
    - HEOSpawn: HEOComponents/HEOSpawn.md
    - HEOSpot: HEOComponents/HEOSpot.md
    - HEOObject: HEOComponents/HEOObject.md
    - HEOLODLevel: HEOComponents/HEOLODLevel.md
    - HEOAudio: HEOComponents/HEOAudio.md
    - HEOPlane: HEOComponents/HEOPlane.md
    - HEOClickGuide: HEOComponents/HEOClickGuide.md
    - HEOUVScroller: HEOComponents/HEOUVScroller.md
    - HEOTextPlane: HEOComponents/HEOTextPlane.md
    - HEOParticle: HEOComponents/HEOParticle.md
    - HEOReflectionProbe : HEOComponents/HEOReflectionProbe.md
    - HEOScript: HEOComponents/HEOScript.md
    - HEOMeshCollider: HEOComponents/HEOMeshCollider.md
    - HEODespawnHeight: HEOComponents/HEODespawnHeight.md
    - HEOCollider: HEOComponents/HEOCollider.md
    - HEOAnimation: HEOComponents/HEOAnimation.md
    - HEOShadow: HEOComponents/HEOShadow.md
    - HEOShowFlag : HEOComponents/HEOShowFlag.md
    - HEOAreacollider: HEOComponents/HEOAreacollider.md
    - HEOVideoTrigger: HEOComponents/HEOVideoTrigger.md
    - HEOActionTrigger: HEOComponents/HEOActionTrigger.md
- Actions: 
    #- ActionNodeGraph: Actions/ActionNodeGraph.md #整備のために一旦取り下げ
    - Actions Overview: Actions/ActionsOverview.md
    - Openweb: Actions/System/Openweb.md
    - Play/StopItem: Actions/Item/PlayStopItem.md
    - Show/HideItem: Actions/Item/ShowHideItem.md
    - Play/StopObject: Actions/Avatar/PlayStopObject.md
    - Show/HideObject: Actions/Avatar/ShowHideObject.md
    - Show/HideNode: Actions/Node/ShowHideNode.md
    - Enable/DisableClickableNode: Actions/Node/EnableDisableClickableNode.md
    - Enable/DisableCollider: Actions/Node/EnableDisableCollider.md
    - Wait: Actions/System/Wait.md
    - SetPosRelativePlayer: Actions/Item/SetPosRelativePlayer.md
    - MoveTo: Actions/Item/MoveTo.md
    - Random: Actions/Programmatic/Random.md
    - Warp: Actions/System/Warp.md
    - JumpWorld: Actions/System/JumpWorld.md
    - Emote: Actions/Avatar/Emote.md
    - Motion: Actions/Avatar/Motion.md
    - NextMotion: Actions/Avatar//NextMotion.md
    - AddVar: Actions/Programmatic/AddVar.md
    - SetVar: Actions/Programmatic/SetVar.md
    - If A == B: Actions/Programmatic/IfEqual.md
    - If A != B: Actions/Programmatic/IfNotEqual.md
    - If A >= B: Actions/Programmatic/IfGreaterThanOrEqual.md
    - If A <= B: Actions/Programmatic/IfLessThanOrEqual.md
    - StopVideo: Actions/System/StopVideo.md
    - SetCookieText: Actions/Programmatic/SetCookieText.md
    - OpenComicViewer: Actions/System/OpenComicViewer.md
    - ShowLayer: Actions/System/ShowLayer.md
    - CallJavaScript: Actions/Programmatic/CallJavaScript.md
    - Enter/LeaveVoiceGroup: Actions/System/EnterLeaveVoiceGroup.md
    - WhiteOut/In: Actions/System/WhiteOutIn.md
    - FadeOut/In: Actions/System/FadeOutIn.md
- HeliScript:
    - Built-in Types:
        - Basic Types: hs/hs_var.md
        - String: hs/hs_string.md
        - List: hs/hs_list.md
    - Class: hs/hs_class.md
    - Component: hs/hs_component.md
    - Built-in Classes And Functions:
        - Vector3: hs/hs_struct_vector3.md
        - Quaternion: hs/hs_struct_quaternion.md
        - Matrix: hs/hs_struct_matrix.md
        - Item: hs/hs_class_item.md
        - Player: hs/hs_class_player.md
    - Built-in Functions:
        - System: hs/hs_system_function.md
        - Math: hs/hs_system_function_math.md
        - Network: hs/hs_system_function_net.md
        - NamePlate: hs/hs_system_function_nameplate.md
        - JavaScript: hs/hs_system_function_js.md
        - GUI: hs/hs_system_function_gui.md
        - TextChat: hs/hs_system_function_textchat.md
    - Statements and flow control:
        - Declarations and definitions: hs/hs_statement_def.md
        - Control Statement: hs/hs_statement_constrol.md
        - Operator: hs/hs_operator.md
- Trouble shooting:
    - SDK does not appear after install : troubleshooting/InstallingDeeplink.md
    - Build Error: troubleshooting/BuildError.md
    - Browser does not open: troubleshooting/BrowserNotOpen.md
    - Browser window blackouts: troubleshooting/BrowserBlackWindow.md
    - Changes are not applied: troubleshooting/ChangesAreNotApplied.md
    - Missing Components After Version Update: troubleshooting/MissingComponents.md
    - Unity settings for replicating actual look in Vket Cloud : heoexporter/he_align_unity_to_vketcloud.md
    - World URL does not open the world: troubleshooting/URLError.md
    - Private room indication disappears on reloading the world check page: troubleshooting/PrivateDisappear.md
- Release Note:
    - v5.x:
        - v5.4: releasenote/releasenote-5.4.md
        - v5.3: releasenote/releasenote-5.3.md
        - v5.2: releasenote/releasenote-5.2.md
        - v5.1: releasenote/releasenote-5.1.md
        - v5.0: releasenote/releasenote-5.0.md
    - v4.x:
        - v4.8: releasenote/releasenote-4.8.md
        - v4.7: releasenote/releasenote-4.7.md
        - v4.6: releasenote/releasenote-4.6.md
        - v4.5: releasenote/releasenote-4.5.md
        - v4.4: releasenote/releasenote-4.4.md
        - v4.3: releasenote/releasenote-4.3.md
        - v4.2: releasenote/releasenote-4.2.md
        - v4.1: releasenote/releasenote-4.1.md
        - v4.0: releasenote/releasenote-4.0.md
    - v3.x:
        - v3.9: releasenote/releasenote-3.9.md  
        - v3.8: releasenote/releasenote-3.8.md
        - v3.7: releasenote/releasenote-3.7.md
        - v3.6: releasenote/releasenote-3.6.md
        - v3.5: releasenote/releasenote-3.5.md
        - v3.4: releasenote/releasenote-3.4.md
        - v3.3: releasenote/releasenote-3.3.md
        - v3.2: releasenote/releasenote-3.2.md
- Change Log:
    - v5.x:
        - v5.4: changelog/changelog-5.4.md
        - v5.3: changelog/changelog-5.3.md
        - v5.2: changelog/changelog-5.2.md
        - v5.1: changelog/changelog-5.1.md
        - v5.0: changelog/changelog-5.0.md
    - v4.x:
        - v4.8: changelog/changelog-4.8.md
        - v4.7: changelog/changelog-4.7.md
        - v4.6: changelog/changelog-4.6.md
        - v4.5: changelog/changelog-4.5.md
        - v4.4: changelog/changelog-4.4.md
        - v4.3: changelog/changelog-4.3.md
        - v4.2: changelog/changelog-4.2.md
        - v4.1: changelog/changelog-4.1.md
        - v4.0: changelog/changelog-4.0.md
    - v3.x:
        - v3.9: changelog/changelog-3.9.md  
        - v3.8: changelog/changelog-3.8.md
        - v3.7: changelog/changelog-3.7.md
        - v3.6: changelog/changelog-3.6.md
        - v3.5: changelog/changelog-3.5.md
        - v3.4: changelog/changelog-3.4.md
        - v3.3: changelog/changelog-3.3.md
        - v3.2: changelog/changelog-3.2.md
- License: common/License.md
